name: CI

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:
  build:
    runs-on: ubuntu-latest
    container: orbisdev/orbisdev-sdkvanilla:latest
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        apk add build-base clang

    - name: Compile orbislib
      run: |
        export PS4SDK=$ORBISDEV
        ls -lR $PS4SDK
        make clean all install
